[project]
name = "tool-calling-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hyperpocket-langgraph>=0.3.6",
    "langchain-openai>=0.3.6",
]
